#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

XRESOURCES=$HOME/.Xresources
export LANG=en_US.utf8

[ -r $XRESOURCES ] && xrdb -merge $XRESOURCES
[ $(which nvidia-settings) ] && nvidia-settings -a InitialPixmapPlacement=2

setxkbmap -option caps:escape

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# exec wmaker
# exec icewm
# exec blackbox
# exec fluxbox
# exec openbox-session
# ...or the Window Manager of your choice

if [ -n "$1" ]
then
	[ -n "$(which $1)" ] && exec $1
else
	exec i3
fi
