#!/usr/bin/env zsh

# Zsh configuration

# With help from these sources:
# https://github.com/slashbeast/things/blob/master/configs/DOTzshrc
# https://github.com/spicycode/ze-best-zsh-config
# http://zanshin.net/2013/02/02/zsh-configuration-from-the-ground-up/

autoload -U compinit promptinit colors vcs_info
colors
compinit
promptinit

test -r $HOME/.aliases && source $HOME/.aliases

for i in $HOME/.zsh.d/*; do;
    test -r "$i" && source "$i"
done
